version: "3.7"

services:
  nodejs-dev:
    container_name: nodejs-dev
    hostname: nodejs-dev.local
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
    networks:
      nodejs-dev-net:

networks:
  nodejs-dev-net:
